slavnejshev/config/routes.rb
Rails.application.routes.draw do
  namespace :private do
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
    
    resources :users
    resources :folders, only: [:create, :update]
    resources :panoramas, only: [:create, :update, :destroy]
    
    resources :panoramas do
      resources :pano_versions, only: [:create]
    end
    resources :pano_versions, only: [:update, :destroy]
    
    get 'roots', to: 'folders#index'
    get 'roots/new', to: 'folders#new'
    
    get 'files/*id', to: 'folders#show', as: 'files'
    get 'pano/*id/version/:version/images/:image_name', to: 'panoramas#image'
    get 'pano/*id/images/:image_name', to: 'panoramas#image'
    get 'pano/*id/version/:version', to: 'panoramas#show', as: 'show_pano_version'
    get 'pano/*id', to: 'panoramas#show', as: 'show_pano'
    get 'data/*id', to: 'data#show', as: 'show_datum'
  end
end

slavnejshev/app/models/private.rb
module Private
  def self.table_name_prefix
    'private_'
  end
end

slavnejshev/app/models/private/datum.rb
class Private::Datum < ApplicationRecord
  validates :path,
    presence: true,
    uniqueness: true
  
  validates :datum_hash,
    presence: true,
    uniqueness: true
  
  has_many :files
  
  def self.digest(datum)
    Digest::SHA1.hexdigest(datum)
  end
end

slavnejshev/app/models/private/file.rb
class Private::File < ApplicationRecord
  validates :original_name,
    presence: true,
    length: { maximum: 256 }
    
  validates :key,
    presence: true,
    length: { maximum: 1024 },
    uniqueness: true
    
  validates :file_type, presence: true
  enum file_type: [ :ordinary, :pano_config, :pano_tile, :pano_hotspot_image ]
  
  def to_param
    key
  end
  
  validates :datum_id, presence: true
  belongs_to :datum
  belongs_to :storage, polymorphic: true
end

slavnejshev/app/models/private/folder.rb
class Private::Folder < ApplicationRecord
  VALID_NAME = /\A[a-z0-9_]+\z/i
  validates :name,
    presence: true,
    length: { maximum: 50 },
    format: { with: VALID_NAME }
    
  validates :title,
    length: { maximum: 50 }
    
  validates :full_path,
    presence: true,
    uniqueness: true
  
  validates :owner_id, presence: true
  belongs_to :owner, class_name: "Private::User", foreign_key: "owner_id"
  has_many :panoramas
  
  before_validation :make_full_path
  
  acts_as_tree
  
  def readable_name
    title.present? ? title : name
  end
  
  def to_param
    full_path
  end
  
  def update_paths
    make_full_path
  end
  
  private
    def make_full_path
      if root?
        self.full_path = name.to_s
      else
        self.full_path = parent.full_path + "/" + name.to_s
      end
    end
end

slavnejshev/app/models/private/pano_version.rb
class Private::PanoVersion < ApplicationRecord
  validates :idx,
    presence: true,
    uniqueness: {scope: :panorama_id},
    numericality: { greater_than: 0 }
  
  validates :description,
    length: { maximum: 1000 }
    
  has_one :config, -> { where file_type: :pano_config }, as: :storage, class_name: 'Private::File', dependent: :destroy
  has_many :tiles, -> { where file_type: :pano_tile }, as: :storage, class_name: 'Private::File', dependent: :destroy
  has_many :hotspots, -> { where file_type: :pano_hotspot_image }, as: :storage, class_name: 'Private::File', dependent: :destroy
  
  belongs_to :panorama
  
  def min_pano?
    config.present? && tiles.present?
  end
  
  def full?
    min_pano? && hotspots.present?
  end
end

slavnejshev/app/models/private/panorama.rb
class Private::Panorama < ApplicationRecord
  VALID_NAME = /\A[a-z0-9_]+\z/i
  validates :name,
    presence: true,
    length: { maximum: 50 },
    format: { with: VALID_NAME }
    
  validates :title,
    length: { maximum: 50 }
    
  validates :description,
    length: { maximum: 1000 }

  validates :full_path,
    presence: true,
    uniqueness: true
  
  validates :folder_id, presence: true
  belongs_to :folder
  has_many :versions, class_name: "Private::PanoVersion", dependent: :destroy
  has_one :owner, through: :folder
  
  before_validation :make_full_path
  
  def readable_name
    title.present? ? title : name
  end
  
  def to_param
    full_path
  end
  
  def update_paths
    make_full_path
  end
  
  def public?
    folder.public?
  end
  
  private
    def make_full_path
      unless folder_id.nil?
        self.full_path = folder.full_path + "/" + name.to_s        
      end
    end
end

slavnejshev/app/controllers/private/data_controller.rb
class Private::DataController < ApplicationController
  include Private::SessionsHelper
  
  before_action :has_right_to_see, only: [:show]
  
  def show
    send_file(@file.datum.path, filename: @file.original_name)
  end
  
  private
    def has_right_to_see
      key = params[:id]
      key += "." + params[:format] unless params[:format].nil? 
      @file = Private::File.find_by(key: key) or not_found
      if @file.file_type.in? [ 'pano_config', 'pano_tile', 'pano_hotspot_image' ]
        panoVersion = @file.storage
        check_right_to_see(panoVersion.panorama.folder)        
      end
    end
end

slavnejshev/app/controllers/private/folders_controller.rb
class Private::FoldersController < ApplicationController
  layout 'private/layout'
  
  include Private::SessionsHelper
  
  before_action :logged_in_user, only: [:new, :index, :create, :update]
  before_action :admin_user, only: [:new, :index]
  before_action :has_right_to_see, only: [:show]
  before_action :has_right_to_create, only: [:create]
  before_action :has_right_to_update, only: [:update]
  
  def new
    @folder = Folder.new
  end
  
  def create
    folder_params = params.require(:private_folder).permit(:name, :parent_id, :public, :stores_panoramas)
    @folder = Folder.new(folder_params)
    @folder.owner = User.find_by(name: params[:private_folder][:owner])
    if @folder.save
      flash[:success] = t(:created_folder)
      redirect_to_parent_or private_roots_path
    else
      flash[:danger] = t(:wrong_folder_params)
      redirect_to_parent_or private_roots_new_path
    end
  end

  def show
    @folder = Folder.find_by(full_path: params[:id])
  end

  def index
    @folders = Folder.roots
  end
  
  def update
    folder_params = params.require(:private_folder).permit(:title)
    @folder.update_attributes(folder_params)
    redirect_to private_files_path(@folder)
  end
  
  private
    def has_right_to_see
      @folder = Folder.find_by(full_path: params[:id])
      check_right_to_see(@folder)
    end
    
    def has_right_to_create
      @parent = Folder.find_by(id: params[:private_folder][:parent_id])
      if @parent.nil?
        admin_user
      else
        if @parent.owner.name == params[:private_folder][:owner]
          admin_or_owner_of(@parent)
        else
          flash[:danger] = t(:access_denied)
          redirect_to current_user
        end
      end
    end
    
    def has_right_to_update
      @folder = Folder.find(params[:id])
      has_right_to_change_files_in(@folder)
    end
    
    def redirect_to_parent_or(path)
      redirect_to_folder_or(@parent, path)
    end
end

slavnejshev/app/controllers/private/pano_versions_controller.rb
class Private::PanoVersionsController < ApplicationController
  include Private::SessionsHelper
  include Private::DataHelper
  Panorama = Private::Panorama
  PanoVersion = Private::PanoVersion
  
  before_action :logged_in_user, only: [:create, :update, :destroy]
  before_action :has_right_to_create, only: [:create]
  before_action :has_right_to_update, only: [:update, :destroy]
  
  MEMBERS = {config: :pano_config, tiles: :pano_tile, hotspots: :pano_hotspot_image}
  
  def create
    next_index = 1
    unless @panorama.versions.empty?
      next_index = @panorama.versions.maximum("idx") + 1
    end
    @panorama.versions.create!(idx: next_index)
    redirect_to private_show_pano_version_path(@panorama, next_index)
  end
  
  def update
    if params.key?(:private_pano_version)
      pano_version_params = params.require(:private_pano_version).permit(:description)
      @pano_version.update_attributes(pano_version_params)
      if @pano_version.config.nil? && params[:private_pano_version][:config].present?
        config_io = params[:private_pano_version][:config]
        make_pano_file(config_io.original_filename, config_io.read, :pano_config)
      end
      if @pano_version.tiles.empty? && params[:private_pano_version][:tiles].present?
        unzip_pano_archive(params[:private_pano_version][:tiles], :pano_tile)
      end
      if @pano_version.hotspots.empty? && params[:private_pano_version][:hotspots].present?
        unzip_pano_archive(params[:private_pano_version][:hotspots], :pano_hotspot_image)
      end
    end
    
    MEMBERS.each do |member_name, file_type|
      param = params[member_name.to_s + "_src"]
      if param.present? && @pano_version.send(member_name).blank?
        src_version = PanoVersion.find(param)
        copy_files(src_version, @pano_version, file_type)
      end
    end
      
    if @pano_version.config.nil? && params[:config_src].present?
      
    end
    
    redirect_to private_show_pano_version_path(@panorama, @pano_version.idx)
  end
  
  def destroy
    @pano_version.destroy
    redirect_to private_show_pano_path(@panorama)
  end
  
  private
    def has_right_to_create
      @panorama = Panorama.find_by(id: params[:panorama_id])
      has_right_to_update_panorama
    end
    
    def has_right_to_update
      @pano_version = PanoVersion.find_by(id: params[:id])
      @panorama = @pano_version.panorama unless @pano_version.nil?
      has_right_to_update_panorama
    end
    
    def has_right_to_update_panorama
      if @panorama.nil?
        flash[:danger] = t(:access_denied)
        redirect_to current_user
      else
        has_right_to_change_files_in(@panorama.folder)
      end
    end
end

slavnejshev/app/controllers/private/panoramas_controller.rb
class Private::PanoramasController < ApplicationController
  layout 'private/layout'
  
  include Private::SessionsHelper
  Panorama = Private::Panorama
  
  before_action :logged_in_user, only: [:create, :update, :destroy]
  before_action :has_right_to_see, only: [:show, :image]
  before_action :has_right_to_create, only: [:create]
  before_action :has_right_to_update, only: [:update, :destroy]
  
  def show
    calc_version
  end
  
  def image
    calc_version || not_found
    key = 'pano/' + @version.id.to_s + '/images/' + params[:image_name]
    key += "." + params[:format] unless params[:format].nil? 
    redirect_to private_show_datum_path(key)
  end
  
  def create
    panorama_params = params.require(:private_panorama).permit(:name, :folder_id)
    @panorama = Panorama.new(panorama_params)
    if @panorama.save
      flash[:success] = t(:created_panorama)
      redirect_to private_show_pano_path(@panorama)
    else
      flash[:danger] = t(:wrong_panorama_params)
      if @folder.nil?
        redirect_to current_user
      else
        redirect_to private_files_path(@folder)
      end
    end
  end
  
  def update
    panorama_params = params.require(:private_panorama).permit(:description, :title)
    @panorama.update_attributes(panorama_params)
    redirect_to private_show_pano_path(@panorama)
  end
  
  def destroy
    folder = @panorama.folder
    @panorama.destroy
    flash[:success] = t(:destroyed_panorama)
    redirect_to private_files_path(folder)
  end
  
  private
    def calc_version
      version_index = params[:version]
      if version_index.nil?
        unless @panorama.versions.empty?
          @version = @panorama.versions.last
        end
      else
        @version = @panorama.versions.find_by(idx: version_index)
      end
      return @version
    end
  
    def has_right_to_see
      @panorama = Panorama.find_by(full_path: params[:id])
      check_right_to_see(@panorama.folder)
    end
    
    def has_right_to_create
      @folder = Folder.find_by(id: params[:private_panorama][:folder_id])
      has_right_to_change_files_in(@folder)
    end
    
    def has_right_to_update
      @panorama = Panorama.find(params[:id])
      has_right_to_change_files_in(@panorama.folder)
    end
end

slavnejshev/app/controllers/private/sessions_controller.rb
class Private::SessionsController < ApplicationController
  layout 'private/layout'
  
  include Private::SessionsHelper
  
  def new
  end
  
  def create
    @user = User.find_by(name: params[:session][:name])
    if @user && @user.authenticate(params[:session][:password])
      log_in @user
      redirect_to @user
    else
      flash.now[:danger] = t(:bad_name_password_pair)
      render 'new'
    end
  end
  
  def destroy
    log_out
    redirect_to private_login_path
  end
end

slavnejshev/app/controllers/private/users_controller.rb
class Private::UsersController < ApplicationController
  include Private::SessionsHelper
  
  before_action :logged_in_user
  before_action :admin_or_correct_user, only: [:show]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: [:index, :new, :create, :destroy]
  
  def show
    @user = find_user
  end

  def index
    @users = User.all
  end

  def edit
  end
  
  def update
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = t(:created_user)
      redirect_to private_users_path
    else
      flash[:danger] = t(:wrong_user_params)
      redirect_to new_private_user_path
    end
  end
  
  private
    def correct_user
      @user = find_user
      unless current_user?(@user)
        flash[:danger] = t(:access_denied)
        redirect_to current_user
      end
    end
    
    def admin_or_correct_user
      unless current_admin?
        correct_user
      end
    end
    
    def find_user
      User.friendly.find(params[:id])
    end
    
    def user_params
      params.require(:private_user).permit(:name, :email, :password, :password_confirmation)
    end
end

slavnejshev/app/helpers/private/data_helper.rb
module Private::DataHelper
  def get_or_add_datum(file_datum)
    file_hash = Private::Datum.digest(file_datum)
    datum = Private::Datum.find_by(datum_hash: file_hash)
    if datum.nil?
      file_path = 'storage/pano/' + file_hash
      datum = Private::Datum.create!(path: file_path, datum_hash: file_hash)
      FileUtils::mkdir_p Rails.root.join('storage', 'pano')
      File.open(file_path, 'wb') do |file|
        file.write(file_datum)
      end
    end
    datum
  end
  
  def make_prefix(version)
    return "pano/" + version.id.to_s + "/"
  end
  
  def make_pano_file(file_path, file_datum, file_type)
    datum = get_or_add_datum(file_datum)
    key = make_prefix(@pano_version) + file_path
    datum.files.create(
      original_name: File.basename(file_path), key: key, storage: @pano_version, file_type: file_type)
  end
  
  def unzip_pano_archive(archive, file_type)
    require 'zip'
    archive_name = archive.original_filename
    Zip::File.open(archive.tempfile) do |zip_file|
      zip_file.each do |entry|
        next unless entry.file?
        make_pano_file(entry.name, entry.get_input_stream.read, file_type)
      end
    end
  end
  
  def copy_files(from_version, to_version, file_type)
    old_prefix = make_prefix(from_version)
    new_prefix = make_prefix(to_version)
    Private::File.where(file_type: file_type, storage: from_version).each do |file|
      new_file = file.dup
      new_file.storage = to_version
      new_file.key.sub!(old_prefix, new_prefix)
      new_file.save
    end
  end
end

slavnejshev/app/helpers/private/folders_helper.rb
module Private::FoldersHelper
end

slavnejshev/app/helpers/private/pano_versions_helper.rb
module Private::PanoVersionsHelper
end

slavnejshev/app/helpers/private/panoramas_helper.rb
module Private::PanoramasHelper
  def pano_title(pano, version = nil)
    title = pano.readable_name
    if version.nil?
      title
    else
      title + " #" + version.idx.to_s
    end
  end
end

slavnejshev/app/helpers/private/sessions_helper.rb
module Private::SessionsHelper
  User = Private::User
  Folder = Private::Folder
  
  def log_in(user)
    session[:user_id] = user.id
  end
  
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def current_user?(user)
    current_user == user
  end
  
  def logged_in?
    !current_user.nil?
  end
  
  def current_admin?
    current_user && current_user.admin?
  end
  
  def logged_in_user
    unless logged_in?
      require_logging_in      
    end
  end
  
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  
  def require_logging_in
    flash[:danger] = t(:logging_in_required)
    redirect_to private_login_path
  end
    
  def admin_user
    unless current_admin?
      flash[:danger] = t(:access_denied)
      redirect_to current_user
    end
  end
  
  def check_right_to_see(obj)
    unless obj.nil? || obj.public?
      if logged_in?
        admin_or_owner_of(obj)
      else
        require_logging_in
      end
    end
  end
  
  def admin_or_owner_of?(folder)
    current_user?(folder.owner) || current_admin?
  end
  
  def admin_or_owner_of(folder)
    unless folder.nil? || current_user?(folder.owner)
      admin_user
    end
  end
  
  def redirect_to_folder_or(folder, path)
    if folder.nil?
      redirect_to path
    else
      redirect_to private_files_path(folder)
    end
  end
  
  def has_right_to_change_files_in(folder)
    unless folder.nil?
      if folder.stores_panoramas?
        admin_or_owner_of(folder)
      else
        flash[:danger] = t(:access_denied)
        redirect_to private_files_path(folder)
      end
    end
  end
end

slavnejshev/app/helpers/private/users_helper.rb
module Private::UsersHelper
end

slavnejshev/app/views/private/folders/_clearfix.html.erb
<% if index % 2 == 0 %>
  <div class="clearfix hidden-lg-up"></div>
<% end %>
<% if index % 4 == 0 %>
  <div class="clearfix hidden-md-down"></div>
<% end %>

slavnejshev/app/views/private/folders/_entity.html.erb
<div class="entity-block">
  <div class="entity-content">
    <div class="entity-icon">
      <%= link_to image_tag(type.to_s + ".png", alt: type.capitalize), path %>
    </div>
    <div class="entity-name">
      <h4><%= link_to entity.readable_name, path %></h4>
    </div>
  </div>
</div>

slavnejshev/app/views/private/folders/_tools.html.erb
<div class="add-block-header">
  <button class="btn btn-secondary" data-toggle="collapse" href="#add-folder-form">
    <%= t('.subfolder_header_button') %>
  </button>
</div>
<div id="add-folder-form" class="add-block-form collapse">
  <%= form_for(:private_folder, url: private_folders_path, html: { class: 'form-inline' }) do |f| %>
    <%= f.hidden_field :owner, value: folder.owner.name %>
    <%= f.hidden_field :parent_id, value: folder.id %>
    <%= f.hidden_field :public, value: (folder.public? ? '1' : '0') %>
    <%= f.hidden_field :stores_panoramas, value: (folder.stores_panoramas? ? '1' : '0') %>
    
    <div class="form-group">
      <%= f.label :name, t('.subfolder_label') %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
      
    <%= f.submit t('.submit_subfolder'), class: 'btn btn-primary' %>
  <% end %>
</div>

<% if folder.stores_panoramas? %>
  <div class="add-block-header">
    <button class="btn btn-secondary" data-toggle="collapse" href="#add-pano-form">
      <%= t('.panorama_header_button') %>
    </button>
  </div>
  <div id="add-pano-form" class="add-block-form collapse">
    <%= form_for(:private_panorama, url: private_panoramas_path, html: { class: 'form-inline' }) do |f| %>
      <%= f.hidden_field :folder_id, value: folder.id %>
    
      <div class="form-group">
        <%= f.label :name, t('.panorama_label') %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      
      <%= f.submit t('.submit_panorama'), class: 'btn btn-primary' %>
    <% end %>
  </div>
<% end %>

slavnejshev/app/views/private/folders/index.html.erb
<% provide(:title, t('.content_title')) %>

<% content_for :block_content do %>
  <% @folders.each do |folder| %>
    <p><%= link_to folder.name, private_files_path(folder) %></p>
  <% end %>
<% end %>

slavnejshev/app/views/private/folders/new.html.erb
<% provide(:title, t('.content_title')) %>

<% content_for :block_content do %>
  <div class="container">
    <%= form_for(@folder) do |f| %>
      <div class="form-group row">
        <%= f.label :name, t('.name_label'), class: 'col-md-3 offset-lg-1 col-lg-2 col-form-label col-form-label-lg' %>
        <div class="col-md-8">
          <%= f.text_field :name, class: 'form-control form-control-lg' %>
        </div>
      </div>
      
      <div class="form-group row">
        <%= f.label :owner, t('.owner_label'), class: 'col-md-3 offset-lg-1 col-lg-2 col-form-label col-form-label-lg' %>
        <div class="col-md-8">
          <%= f.text_field :owner, class: 'form-control form-control-lg' %>
        </div>
      </div>
      
      <div class="row">
        <div class="offset-md-3 col-md-8">
          <div class="form-check">
            <label class="form-check-label form-check-label-lg">
              <%= f.check_box :public, class: 'form-check-input' %><%= t('.public_label') %>
            </label>
          </div>
        </div>
      </div>
      
      <div class="form-group row">
        <div class="offset-md-3 col-md-8">
          <div class="form-check">
            <label class="form-check-label form-check-label-lg">
              <%= f.check_box :stores_panoramas, class: 'form-check-input' %><%= t('.panoramas_label') %>
            </label>
          </div>
        </div>
      </div>
      
      <div class="row">
        <div class="col-md-6 offset-md-3">
          <%= f.submit t('.submit_root'), class: 'btn btn-primary btn-lg btn-block' %>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

slavnejshev/app/views/private/folders/show.html.erb
<% provide(:title, @folder.readable_name) %>
<% provide(:block_title, t('.obj_name') + ' "' + @folder.readable_name + '"') %>

<% editable = admin_or_owner_of?(@folder) %>

<% content_for :on_block_top do %>
  <%= render partial: 'shared/path', locals: { full_path: @folder.full_path  } %>
<% end %>

<% content_for :block_header do %>
  <%= render partial: 'shared/tags', locals: { obj: @folder  } %>
  <%= render partial: 'shared/title', locals: {
    obj: @folder, url_path: private_folder_path(@folder.id), editable: editable } %>
<% end %>
      
<% content_for :block_content do %>
  <% if admin_or_owner_of?(@folder) %>
    <%= render partial: 'tools', locals: { folder: @folder  } %>
  <% end %>
  <div class="row">
    <% @folder.children.each_with_index do |folder, index| %>
      <%= render partial: 'entity', locals: { entity: folder, type: :folder, path: private_files_path(folder) } %>
      <%= render partial: 'clearfix', locals: { index: index + 1 } %>
    <% end %>
    <% folders_num = @folder.children.count %>
    <% @folder.panoramas.each_with_index do |panorama, index| %>
      <%= render partial: 'entity', locals: { entity: panorama, type: :panorama, path: private_show_pano_path(panorama) } %>
      <%= render partial: 'clearfix', locals: { index: folders_num + index + 1 } %>
    <% end %>
  </div>
<% end %>