slavnejshev/config/routes.rb
Rails.application.routes.draw do
  namespace :private do
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
    
    resources :users
    resources :folders, only: [:create, :update]
    resources :panoramas, only: [:create, :update, :destroy]
    
    resources :panoramas do
      resources :pano_versions, only: [:create]
    end
    resources :pano_versions, only: [:update, :destroy]
    
    get 'roots', to: 'folders#index'
    get 'roots/new', to: 'folders#new'
    
    get 'files/*id', to: 'folders#show', as: 'files'
    get 'pano/*id/version/:version/images/:image_name', to: 'panoramas#image'
    get 'pano/*id/images/:image_name', to: 'panoramas#image'
    get 'pano/*id/version/:version', to: 'panoramas#show', as: 'show_pano_version'
    get 'pano/*id', to: 'panoramas#show', as: 'show_pano'
    get 'data/*id', to: 'data#show', as: 'show_datum'
  end
end

slavnejshev/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-dark bg-inverse">
      <a class="navbar-brand" href="#"><%= t(:title) %></a>
      <ul class="nav navbar-nav">
        <% if private_namespace? %>
          <li class="nav-item">
            <% if logged_in? %>
              <%= link_to t(:logout), private_logout_path, method: :delete, class: 'nav-link' %>
            <% else %>
              <%= link_to t(:login), private_login_path, class: 'nav-link' %>
            <% end %>
          </li>
        <% end %>
      </ul>
    </nav>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= content_for?(:content) ? yield(:content) : yield %>
    </div>
  </body>
</html>