slavnejshev/config/routes.rb
Rails.application.routes.draw do
  namespace :private do
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
    
    resources :users
    resources :folders, only: [:create, :update]
    resources :panoramas, only: [:create, :update, :destroy]
    
    resources :panoramas do
      resources :pano_versions, only: [:create]
    end
    resources :pano_versions, only: [:update, :destroy]
    
    get 'roots', to: 'folders#index'
    get 'roots/new', to: 'folders#new'
    
    get 'files/*id', to: 'folders#show', as: 'files'
    get 'pano/*id/version/:version/images/:image_name', to: 'panoramas#image'
    get 'pano/*id/images/:image_name', to: 'panoramas#image'
    get 'pano/*id/version/:version', to: 'panoramas#show', as: 'show_pano_version'
    get 'pano/*id', to: 'panoramas#show', as: 'show_pano'
    get 'data/*id', to: 'data#show', as: 'show_datum'
  end
end

slavnejshev/app/views/shared/_description.html.erb
<% desc_form_id_prefix = obj.class.name.demodulize.downcase %>
<div class="description-main-block">
  <% if editable %>
    <a class="description-edit-button" data-toggle="collapse" href="#<%= desc_form_id_prefix %>-description-form">
      <%= t('.edit_description') %>
    </a>
  <% end %>
  <b><%= t('.description_label') %></b> 
  <span id="description-text"><%= (obj.description.blank? ? t('.empty_description') : obj.description) %></span>
</div>
<% if editable %>
  <div class="description-form collapse" id="<%= desc_form_id_prefix %>-description-form">
    <%= form_for(obj, url: url_path) do |f| %>
      <div class="form-group">
        <%= f.text_area :description, placeholder: t('.suggest_write_description'), rows: 3, class: 'form-control' %>
      </div>
      <%= f.submit t('.submit_description'), class: "btn btn-secondary" %>
    <% end %>
  </div>
<% end %>

slavnejshev/app/views/shared/_path.html.erb
<ol class="breadcrumb path-block">
  <% cur_path = '' %>
  <% full_path.split('/').each do |dir_name| %>
    <% cur_path += '/' unless cur_path.empty? %>
    <% cur_path += dir_name %>
    <% is_last = cur_path == full_path %>
    <li class="breadcrumb-item <%= 'active' if is_last %>">
      <% if is_last %>
        <%= dir_name %>
      <% else %>
        <%= link_to dir_name, private_files_path(cur_path) %>
      <% end %>
    </li>
  <% end %>
</ol>

slavnejshev/app/views/shared/_tags.html.erb
<div class="obj-tags">
  <span class="tag tag-default"><%= t('.owner') + obj.owner.name %></span>
  <% if obj.public? %>
    <span class="tag tag-info"><%= t('.public') %></span>
  <% else %>
    <span class="tag tag-warning"><%= t('.private') %></span>
  <% end %>
  <% if obj.respond_to?('stores_panoramas?') %>
    <% if obj.stores_panoramas? %>
      <span class="tag tag-info"><%= t('.panorama') %></span>
    <% end %>
  <% end %>
</div>

slavnejshev/app/views/shared/_title.html.erb
<% title_form_id_prefix = obj.class.name.demodulize.downcase %>
<div class="file-name-block">
  <b><%= t('.file_name_label') %></b> 
  <span id="file-name-text"><%= obj.name %></span>
</div>
<div class="title-main-block">
  <% if editable %>
    <a class="title-edit-button" data-toggle="collapse" href="#<%= title_form_id_prefix %>-title-form">
      <%= t('.edit_title') %>
    </a>
  <% end %>
  <b><%= t('.title_label') %></b> 
  <span id="title-text"><%= (obj.title.blank? ? t('.empty_title') : obj.title) %></span>
</div>
<% if editable %>
  <div class="title-form collapse" id="<%= title_form_id_prefix %>-title-form">
    <%= form_for(obj, url: url_path) do |f| %>
      <div class="form-group">
        <%= f.text_field :title, class: 'form-control' %>
      </div>
      <%= f.submit t('.submit_title'), class: "btn btn-secondary" %>
    <% end %>
  </div>
<% end %>